baseurl: https://example.com
title: Hugo DPSG
languageCode: de
DefaultContentLanguage: de
paginate: '10'
theme: hugo-dpsg
Author:
  avatar: img/avatar.png
  bio: The Scout Master is the leader of this local scout group
  name: Scout Master
Params:
  authorbox: yes
  copyright: DGSP local group
  dateformat: 02.01.2006
  description: Welcome to our scout group!
  footer:
    right: Donate!
    text: '[Imprint and Privacy](/imprint)'
  indexPager: yes
  logo:
    header: img/header.jpg
    image: img/placeholder.png
    subtitle: Welcome to our group site
    title: Hugo DPSG
  mainSections:
    - post
    - blog
    - news
  opengraph: yes
  pager: yes
  post_meta:
    - author
    - date
    - categories
    - translations
  readmore: no
  schema: yes
  sidebar:
    home: right
    list: left
    single: no
    widgets:
      - search
      - recent
      - categories
      - taglist
      - social
      - languages
  style:
    vars:
      highlightColor: '#003056'
  toc: yes
  twitter_cards: yes
  widgets:
    recent_num: 5
    tags_counter: no
menu:
  main:
    - identifier: start
      name: Start
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 2
